-- return {
--     "iamcco/markdown-preview.nvim",
--     cmd = { "MarkdownPreviewToggle", "MarkdownPreview", "MarkdownPreviewStop" },
--     build = "cd ~/.local/share/nvim/lazy/markdown-preview.nvim/ && npm install",
--     init = function()
--         vim.g.mkdp_filetypes = { "markdown" }
--     end,
--     ft = { "markdown" },
-- }
